apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: max-weather
  template:
    metadata:
      labels:
        app: max-weather
    spec:
      containers:
      - name: max-weather
        image: <IMAGE_URI>
        ports:
        - containerPort: 8000
